### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by fbclh** [Sahar-AbdelSamad/Portfolio-setup-and-mobile-version-skeleton#14]
- Your project is looking very good! Clean and easy to understand code.
- I would suggest to leave the error message in red and add an exclamation icon in front of it for better UX. (But is totally up to you)

**Comment by Sahar-AbdelSamad** [comment]
> * Your project is looking very good! Clean and easy to understand code.
> 
>     * I would suggest to leave the error message in red and add an exclamation icon in front of it for better UX. (But is totally up to you)

Thank you :smile: and well noted :+1:
