### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by mukhammadrizooff** [Sahar-AbdelSamad/Portfolio-setup-and-mobile-version-skeleton#7]
It was Wonderful :)
[Optional]
-Try to use Icon (like Fontawesome icons) instead of img for the social media element.

**Comment by fbclh** [comment]
- Your project is looking very good! Clean and easy to understand code.
- I would suggest to leave the error message in red and add an exclamation icon in front of it for better UX. (But is totally up to you)

**Comment by Sahar-AbdelSamad** [comment]
> It was Wonderful :) [Optional] -Try to use Icon (like Fontawesome icons) instead of img for the social media element.

Well noted :+1: thank you :smile:
