### ISSUE TITLE
Morning code Review

### ISSUE THREAD

**Issue by JohnFTitor** [Sahar-AbdelSamad/Portfolio-setup-and-mobile-version-skeleton#9]
# Hello @Sahar-AbdelSamad 👋🏻 

You've done a great job so far 💯 

## To highlight 🎉  

- ✅  The website is working properly and follows the template perfectly.
- ✅  The code is pretty clean and organized. I loved the usage of classes in CSS.

## Suggestions 🚀 🚀 

- [x] Add a transition to the contact form.
- [x] Change the image on the README.md file to a video.
- [x] Make the navbar stick to the top.
- [x] Use animation shorthand to make it look cleaner.  

## Closing 😸 

Please let me know If you have any questions about my suggestions. We're all here to learn so let's take advantage of different perspectives!
Cheers and happy coding! 👨🏻‍💻 

<img src="https://media1.giphy.com/media/VBc6l3CqQonqo/giphy.gif"/>

**Comment by Sahar-AbdelSamad** [comment]
Thank you for your feedback I implemented the changes successfully!
